name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  docker:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: wendyliga
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: wendyliga
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        if: startsWith(github.ref, 'refs/tags') != true && github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2

      - name: Deploy nightly
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            wendyliga/wrangler:nightly
            ghcr.io/wendyliga/wrangler:nightly
      - name: Deploy release
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            wendyliga/wrangler:${GITHUB_REF#refs/*/}
            wendyliga/wrangler:latest
            ghcr.io/wendyliga/wrangler:${GITHUB_REF#refs/*/}
            ghcr.io/wendyliga/wrangler:latest
